name: CI/CD Pipeline

on: [push, pull_request]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm lint

      - name: Build
        run: pnpm build

      - name: Set up SSH key
        if: github.ref == 'refs/heads/main'
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to VPS
        if: github.ref == 'refs/heads/main'
        run: |
          ssh xlpuser1@${{ secrets.SERVER_IP }} << 'EOF'
            cd ${{ secrets.PROJECT_PATH }} || { echo "Failed to change directory"; exit 1; }
            git pull || { echo "Failed to pull latest code"; exit 1; }
            pnpm install || { echo "Failed to install dependencies"; exit 1; }
            pnpm build || { echo "Failed to build project"; exit 1; }
            pm2 restart ecosystem.config.js || { echo "Failed to restart application"; exit 1; }
          EOF
